version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '8080:8080'
  mysql:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
